import MasonryGrid from "@/components/Masonry-Grid/masonry-grid"
import Head from "next/head"
import { useEffect, useState } from "react"
import { getPhotos } from "@/firebase/get-photos"
import Spinner from "@/components/Spinner/spinner"
import PaginationComponent from "@/components/shared/Pagination/pagination"

function BlackAndWhiteGallery() {
    const [photosData, setPhotosData] = useState([])
    const [currentPage, setCurrentPage] = useState(1)

    const category = 'black-and-white'

    const photosPerPage = 15
    const indexOfLastPhoto = currentPage * photosPerPage
    const indexOfFirstPhoto = indexOfLastPhoto - photosPerPage
    const currentPhotos = photosData.slice(indexOfFirstPhoto, indexOfLastPhoto)

    useEffect(() => {
        fetchData()
    }, [])

    async function fetchData() {
        try {
            const data = await getPhotos(category)
            setPhotosData(data)
        } catch (error) {
            console.error("Error fetching data:", error)
        }
    }

    function handlePageChange(pageNumber) {
        setCurrentPage(pageNumber)
        window.scrollTo({ top: 0, behavior: 'smooth' })
    }

    return (
        <>
            <div>
                <Head>
                    <title>Ksahlos - Stories</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <div className="p-2">
                    {photosData.length > 0 ?
                        <>
                            <MasonryGrid photos={currentPhotos} />
                            <div className="flex justify-center items-center">
                                <PaginationComponent
                                    totalItems={photosData.length}
                                    itemsPerPage={photosPerPage}
                                    currentPage={currentPage}
                                    onPageChange={handlePageChange}
                                />
                            </div>
                        </>
                        : <div className='flex justify-center items-center w-full h-screen'>
                            <Spinner />
                        </div>
                    }
                </div>
            </div>
        </>
    )
}

export default BlackAndWhiteGallery
